threadsCPU: 16 #кол-во потоков на ЦП
threadNums: 8 #кол-во задейсвованных потоков в обработке
multipleResize: 4 #коэффициент сжатия размера изображения
processingSize: 32 #область обработки в пикселях

#Отображение точек на изображении
colorR: 0 #Красный канал
colorG: 255 #Зеленый канал
colorB: 0 #Синий канал
shift: 5 #Сдвиг текста от точки